### ISSUE TITLE
Parser issue with attack_setup()

### ISSUE THREAD

**Issue by Lexx2k** [FakelsHub/sfall_script_editor#12] opened 2019-12-22 11:54 UTC
I can reliably crash the script editor with typing in "attack_setup(..."

Sometimes just typing "attack" and clicking somewhere else already makes the parser go haywire. It usually ends with me having to kill the task and restart the script editor. 

I have to write the code in notepad and copy&paste it into the script editor to get around this.

**Comment by FakelsHub** [comment] 2019-12-22 13:56
Try new dll [parser.zip](https://github.com/FakelsHub/sFall-ScriptEditor/files/3992537/parser.zip)

**Comment by Lexx2k** [comment] 2019-12-22 15:22
That seems to have fixed it. Thanks.

I just remembered another issue: 
If you go to the very last line in a script, then write "procedure somethingsomething begin" and press enter, the script editor will throw an error. This only happens in the very last line.

**Comment by Lexx2k** [comment] 2020-01-25 23:26
I have a new issue related to the parser.

A few days ago I've updated from Win7 to Win10. Now whenever I write code that makes the parser go "Error!", the script editor instead locks up and I have to terminate the task. 
Already had to disable the "live parser" in the settings, but the same happens if I compile the script and there is any error somewhere. It keeps loading and loading and loading.

**Comment by FakelsHub** [comment] 2020-01-26 01:23
I think I won't fix this problem. I don't have win10. Therefore, to fix these problems, you/me need detailed logs about how the program works in this buggy OS.

**Comment by FakelsHub** [comment] 2020-01-26 03:11
You can ask someone from your team rotatоrs who will be able to changes/fix the code and make pull requests here.

**Comment by ghost2238** [comment] 2020-01-26 11:16
> 
> 
> You can ask someone from your team rotatоrs who will be able to changes/fix the code and make pull requests here.

The issue is here: https://github.com/FakelsHub/sFall-ScriptEditor/blob/improve/ScriptEditor/CodeTranslation/Compiler.cs#L83

compiler.exe needs to be called with the "-q" (don't wait for input on error) switch or else it won't exit properly on error and editor will wait indefinitely. I added this and everything works as expected on compile with syntax errors. Lexx confirmed that it's working for him too.

**Comment by FakelsHub** [comment] 2020-02-10 11:02
> compiler.exe needs to be called with the "-q" (don't wait for input on error) 

Apparently win10 contains a bug, the window/process should be closed when the timeout expires, as it happens in other OS.

**Closed as completed by FakelsHub** 2020-02-10 11:02 UTC
